package echowarp

import "time"

// BanKind enumerates the supported ban subject types. A single BanEntry
// targets exactly one subject (IP, HWID, or Nickname). The field-level
// presence on BanEntry selects the kind implicitly; this type is kept for
// future extension and for tests that want to assert kinds explicitly.
type BanKind int

const (
	// BanKindIP bans a remote IP address. The internal ban manager checks
	// this on every incoming signaling connection.
	BanKindIP BanKind = iota
	// BanKindHWID bans a hardware fingerprint sent by the client during
	// authentication handshake (only effective when HWIDRequired is set
	// on the server config).
	BanKindHWID
	// BanKindNickname bans a nickname chosen by the client during
	// authentication. Enforced by the server when constructing the
	// participant record.
	BanKindNickname
)

// BanEntry is a public, transport-agnostic snapshot of a single ban record
// returned by Node.BanList and consumed by Node.AddBan / Node.RemoveBan.
//
// Exactly one of IP, HWID, or Nickname must be non-empty when adding a
// new ban. On listing, existing bans are flattened into a single slice —
// the caller inspects the populated field to determine the ban kind.
//
// ID is a stable identifier derived from the kind + subject (e.g.
// "ip:203.0.113.5", "hwid:abc123", "nick:spammer"). It is generated by
// the Node wrapper on list and is the only accepted form for RemoveBan —
// callers must not fabricate IDs outside this scheme.
type BanEntry struct {
	// ID is the stable server-assigned identifier used by RemoveBan. It
	// has the form "<kind>:<subject>" where kind ∈ {ip,hwid,nick}.
	ID string `json:"id"`

	// IP is the banned remote address (empty when this entry targets
	// HWID or Nickname).
	IP string `json:"ip,omitempty"`

	// HWID is the banned hardware fingerprint (empty when this entry
	// targets IP or Nickname).
	HWID string `json:"hwid,omitempty"`

	// Nickname is the banned nickname (empty when this entry targets
	// IP or HWID).
	Nickname string `json:"nickname,omitempty"`

	// Reason is an optional human-readable justification supplied by
	// the API caller. Currently not persisted by the file-backed ban
	// manager (the internal model has no reason field); populated
	// only on the request path and dropped on list. TODO(task-019):
	// plumb reason through the internal BanEntry once the persistence
	// format is extended.
	Reason string `json:"reason,omitempty"`

	// CreatedAt is when the ban was recorded. For bans listed from the
	// internal manager, this is either the BannedAt timestamp if known
	// or a zero time.Time if the underlying record predates timestamp
	// tracking.
	CreatedAt time.Time `json:"created_at"`
}

// BanEntryRequest is the payload accepted by Node.AddBan and POST
// /api/v1/bans. Exactly one of IP, HWID, or Nickname must be non-empty;
// providing more than one is rejected as invalid to keep the ban kind
// unambiguous (the internal ban manager stores each kind in a separate
// map and a request targeting multiple kinds cannot be rolled back
// atomically on partial failure).
type BanEntryRequest struct {
	IP       string `json:"ip,omitempty"`
	HWID     string `json:"hwid,omitempty"`
	Nickname string `json:"nickname,omitempty"`
	Reason   string `json:"reason,omitempty"`
}
