name: Build and Publish

on:
  push:
    branches:
      - master
  release:
    types:
      - created

jobs:
  get_version:
    name: Get version of package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Extract version from Python script
        id: version
        run: |
          VERSION=$(python -c 'from version import __version__; print(__version__)')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Set output
        id: set_output
        run: |
          echo "::set-output name=version::$VERSION"

      - name: Check if version exists on PyPI
        run: |
            RESPONSE=$(curl -s https://pypi.org/pypi/echowarp/json)
            EXISTS=$(echo $RESPONSE | jq --arg VERSION "$VERSION" '.releases | has($VERSION)')
            if [[ "$EXISTS" == "true" ]]; then
              echo "Version $VERSION already exists on PyPI, stopping job."
              exit 1
            fi

    outputs:
      version: ${{ steps.set_output.outputs.version }}

  build:
    needs: get_version
    name: Build and package
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install system dependencies on Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install -y portaudio19-dev

      - name: Install system dependencies on macOS
        if: matrix.os == 'macos-latest'
        run: brew install portaudio

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine pyinstaller
          pip install -r requirements.txt

      - name: Build dist
        run: |
          python setup.py sdist bdist_wheel

      - name: Build binary with PyInstaller
        run: >
          pyinstaller 
          --noconfirm 
          --paths=./echowarp/ 
          --onefile 
          --name=EchoWarp-${{ needs.get_version.outputs.version }}-${{ matrix.os }}
          ./echowarp/main.py

      - name: Upload Artifacts for each OS
        uses: actions/upload-artifact@v2
        with:
          name: EchoWarp-${{ needs.get_version.outputs.version }}-${{ matrix.os }}
          path: dist/EchoWarp-${{ needs.get_version.outputs.version }}-${{ matrix.os }}${{ matrix.os == 'windows-latest' && '.exe' || '' }}

  release:
    needs: build
    name: Create Release and Publish to PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v2
        with:
          path: dist

      - name: Create and Push Tag
        run: |
            VERSION=${{ needs.get_version.outputs.version }}
            git tag -a $VERSION -m "Release $VERSION"
            git push origin $VERSION

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.get_version.outputs.version }}
          name: Release ${{ needs.get_version.outputs.version }}
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.4.2
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          user: __token__
          repository_url: https://upload.pypi.org/legacy/